package jp.riverapp.hexlide.presentation.localization

data class LocalizedStrings(
    // Mode
    val aiMode: String,
    val pvpMode: String,
    val onlineMode: String,
    val selectMode: String,
    val changeMode: String,

    // Players
    val you: String,
    val ai: String,
    val opponent: String,
    val playerRed: String,
    val playerBlue: String,

    // Phase
    val phaseMoveToken: String,
    val phaseMoveTile: String,

    // Victory
    val youWin: String,
    val aiWin: String,
    val opponentWin: String,
    val redWin: String,
    val blueWin: String,
    val playAgain: String,

    // Status
    val yourTurn: String,
    val opponentTurn: String,
    val decidingFirst: String,

    // Online
    val onlineTitle: String,
    val createRoom: String,
    val joinRoom: String,
    val createGame: String,
    val creating: String,
    val waitingForOpponent: String,
    val shareUrl: String,
    val shareDescription: String,
    val roomCodeLabel: String,
    val enterRoomCode: String,
    val roomCodePlaceholder: String,
    val invalidRoomCode: String,
    val copyUrl: String,
    val copied: String,
    val joining: String,
    val joinGame: String,
    val gameNotFound: String,
    val gameAlreadyStarted: String,
    val endGame: String,
    val confirmEndGame: String,
    val cancel: String,
    val confirm: String,
    val backToLobby: String,
    val back: String,
    val abandoned: String,
    val connectionError: String,
    val reconnecting: String,
    val localMatch: String,

    // Rules
    val goal: String,
    val goalHint: String,
    val slideToEdge: String,
    val moveEmptyTile: String,
    val rulesLabel: String,
    val boardLabel: String,
    val alertBoardSplit: String,
    val confirmRestart: String,
    val restart: String,

    // Common
    val loading: String,
    val aiThinking: String,
    val version: String,

    // Settings
    val settings: String,
    val language: String,
    val howToPlay: String,
    val privacyPolicy: String,
    val contact: String,
    val appWebsite: String,
    val homepage: String,
    val webVersion: String,
    val writeReview: String,
    val done: String,
    val followDeviceSetting: String,
    val deleteLocalData: String,
    val deleteLocalDataConfirm: String,
    val deleteLocalDataComplete: String,
    val delete: String,

    // Stats
    val aiStats: String,
    val statsWins: String,
    val statsLosses: String,
    val statsTotalGames: String,
    val statsWinRate: String,
    val statsAvgTurns: String,
    val statsNoGamesYet: String,
    val statsGameHistory: String,
    val statsTurnsFormat: String,
    val statsFirst: String,
    val statsSecond: String,
) {
    companion object {
        // MARK: - English
        val EN = LocalizedStrings(
            aiMode = "AI Mode",
            pvpMode = "2-Player Mode",
            onlineMode = "Online Mode",
            selectMode = "Select Mode",
            changeMode = "Change Mode",
            you = "You",
            ai = "AI",
            opponent = "Opponent",
            playerRed = "Red",
            playerBlue = "Blue",
            phaseMoveToken = "1. Slide a piece",
            phaseMoveTile = "2. Move a tile",
            youWin = "You win!",
            aiWin = "AI wins!",
            opponentWin = "Opponent wins!",
            redWin = "Red wins!",
            blueWin = "Blue wins!",
            playAgain = "Play again",
            yourTurn = "Your turn",
            opponentTurn = "Opponent's turn",
            decidingFirst = "Deciding who goes first...",
            onlineTitle = "Online Mode",
            createRoom = "Create Room",
            joinRoom = "Join Room",
            createGame = "Create Game",
            creating = "Creating...",
            waitingForOpponent = "Waiting for opponent...",
            shareUrl = "Share this URL with a friend:",
            shareDescription = "Send the room code or URL to a friend.\nJoin by code in the app, or open the URL\nto play instantly on the web.",
            roomCodeLabel = "Room Code",
            enterRoomCode = "Enter room code",
            roomCodePlaceholder = "e.g. 123456",
            invalidRoomCode = "Please check the room code",
            copyUrl = "Copy URL",
            copied = "Copied!",
            joining = "Joining...",
            joinGame = "Join",
            gameNotFound = "Game not found",
            gameAlreadyStarted = "This game has already started",
            endGame = "End Game",
            confirmEndGame = "Are you sure you want to end the game?\nThe connection with your opponent will be terminated.",
            cancel = "Cancel",
            confirm = "End Game",
            backToLobby = "Back to lobby",
            back = "Back",
            abandoned = "Connection interrupted",
            connectionError = "Connection error",
            reconnecting = "Reconnecting...",
            localMatch = "Local Match",
            goal = "Win by connecting your three pieces!",
            goalHint = "Tap for details",
            slideToEdge = "Slide a piece to the edge",
            moveEmptyTile = "Move an empty tile",
            rulesLabel = "Rules",
            boardLabel = "Hexlide game board",
            alertBoardSplit = "You cannot split the board.",
            confirmRestart = "Restart this game?",
            restart = "Restart",
            loading = "Loading...",
            aiThinking = "AI...",
            version = "Version",
            settings = "Settings",
            language = "Language",
            howToPlay = "How to Play",
            privacyPolicy = "Privacy Policy",
            contact = "Contact Us",
            appWebsite = "App Website",
            homepage = "Homepage",
            webVersion = "Web Version",
            writeReview = "Write a Review",
            done = "Done",
            followDeviceSetting = "Follow Device",
            deleteLocalData = "Delete Local Data",
            deleteLocalDataConfirm = "This will reset your player ID and language settings. This cannot be undone.",
            deleteLocalDataComplete = "Local data has been deleted.",
            delete = "Delete",
            aiStats = "AI Battle Stats",
            statsWins = "Wins",
            statsLosses = "Losses",
            statsTotalGames = "Total Games",
            statsWinRate = "Win Rate",
            statsAvgTurns = "Avg. Turns",
            statsNoGamesYet = "No games yet",
            statsGameHistory = "Game History",
            statsTurnsFormat = "%d turns",
            statsFirst = "1st",
            statsSecond = "2nd",
        )

        // MARK: - Japanese
        val JA = LocalizedStrings(
            aiMode = "AI対戦モード",
            pvpMode = "ふたりで対戦モード",
            onlineMode = "オンライン対戦",
            selectMode = "モードを選択",
            changeMode = "モード変更",
            you = "あなた",
            ai = "AI",
            opponent = "相手",
            playerRed = "赤",
            playerBlue = "青",
            phaseMoveToken = "1. コマを滑らせる",
            phaseMoveTile = "2. タイルを動かす",
            youWin = "あなたの勝ち!",
            aiWin = "AIの勝ち!",
            opponentWin = "相手の勝ち!",
            redWin = "赤の勝ち!",
            blueWin = "青の勝ち!",
            playAgain = "もう一度あそぶ",
            yourTurn = "あなたの番",
            opponentTurn = "相手の番",
            decidingFirst = "先攻を決めています...",
            onlineTitle = "オンライン対戦モード",
            createRoom = "ルームを作る",
            joinRoom = "ルームに入る",
            createGame = "ゲームを作成",
            creating = "作成中...",
            waitingForOpponent = "対戦相手を待っています...",
            shareUrl = "このURLを友達に共有:",
            shareDescription = "ルーム番号かURLを友達に送りましょう\nアプリで番号入力、またはURLを開くだけで\nすぐにWeb上で対戦できます",
            roomCodeLabel = "ルーム番号",
            enterRoomCode = "ルーム番号を入力",
            roomCodePlaceholder = "例: 123456",
            invalidRoomCode = "ルーム番号を確認してください",
            copyUrl = "URLをコピー",
            copied = "コピーしました!",
            joining = "参加中...",
            joinGame = "参加する",
            gameNotFound = "ゲームが見つかりません",
            gameAlreadyStarted = "このゲームは既に開始されています",
            endGame = "終了する",
            confirmEndGame = "本当に終了しますか？\n対戦相手との接続が切断されます。",
            cancel = "キャンセル",
            confirm = "終了する",
            backToLobby = "ロビーに戻る",
            back = "戻る",
            abandoned = "接続が中断されました",
            connectionError = "接続エラー",
            reconnecting = "再接続中...",
            localMatch = "ローカル対戦",
            goal = "自分のコマを 3つ連結 させれば勝ち!",
            goalHint = "タップで詳しい説明へ",
            slideToEdge = "端までコマを滑らせる",
            moveEmptyTile = "空きタイルを移動する",
            rulesLabel = "ゲームルール",
            boardLabel = "Hexlide ゲームボード",
            alertBoardSplit = "盤面を分断できません",
            confirmRestart = "ゲームを最初からやり直しますか？",
            restart = "やり直す",
            loading = "読み込み中...",
            aiThinking = "AI...",
            version = "バージョン",
            settings = "設定",
            language = "言語",
            howToPlay = "遊び方",
            privacyPolicy = "プライバシーポリシー",
            contact = "お問い合わせ",
            appWebsite = "アプリ紹介サイト",
            homepage = "ホームページ",
            webVersion = "Web版で遊ぶ",
            writeReview = "レビューを書く",
            done = "完了",
            followDeviceSetting = "端末設定に合わせる",
            deleteLocalData = "ローカルデータを削除",
            deleteLocalDataConfirm = "プレイヤーIDと言語設定がリセットされます。この操作は元に戻せません。",
            deleteLocalDataComplete = "ローカルデータを削除しました。",
            delete = "削除",
            aiStats = "AI対戦成績",
            statsWins = "勝ち",
            statsLosses = "負け",
            statsTotalGames = "合計",
            statsWinRate = "勝率",
            statsAvgTurns = "平均ターン数",
            statsNoGamesYet = "まだ対戦なし",
            statsGameHistory = "対戦履歴",
            statsTurnsFormat = "%dターン",
            statsFirst = "先攻",
            statsSecond = "後攻",
        )

        // MARK: - Korean
        val KO = LocalizedStrings(
            aiMode = "AI 모드",
            pvpMode = "2인 대전 모드",
            onlineMode = "온라인 대전",
            selectMode = "모드 선택",
            changeMode = "모드 변경",
            you = "나",
            ai = "AI",
            opponent = "상대",
            playerRed = "빨강",
            playerBlue = "파랑",
            phaseMoveToken = "1. 말 밀기",
            phaseMoveTile = "2. 타일 이동",
            youWin = "승리!",
            aiWin = "AI 승리!",
            opponentWin = "상대 승리!",
            redWin = "빨강 승리!",
            blueWin = "파랑 승리!",
            playAgain = "다시 하기",
            yourTurn = "내 차례",
            opponentTurn = "상대 차례",
            decidingFirst = "선공을 정하는 중...",
            onlineTitle = "온라인 대전 모드",
            createRoom = "방 만들기",
            joinRoom = "방 참가",
            createGame = "게임 생성",
            creating = "생성 중...",
            waitingForOpponent = "상대를 기다리는 중...",
            shareUrl = "이 URL을 친구에게 공유하세요:",
            shareDescription = "방 코드 또는 URL을 친구에게 보내세요.\n앱에서 코드를 입력하거나 URL을 열면\n바로 웹에서 대전할 수 있습니다.",
            roomCodeLabel = "방 코드",
            enterRoomCode = "방 코드 입력",
            roomCodePlaceholder = "예: 123456",
            invalidRoomCode = "방 코드를 확인해 주세요",
            copyUrl = "URL 복사",
            copied = "복사됨!",
            joining = "참가 중...",
            joinGame = "참가",
            gameNotFound = "게임을 찾을 수 없습니다",
            gameAlreadyStarted = "이미 시작된 게임입니다",
            endGame = "게임 종료",
            confirmEndGame = "정말 게임을 종료하시겠습니까?\n상대와의 연결이 끊어집니다.",
            cancel = "취소",
            confirm = "종료",
            backToLobby = "로비로 돌아가기",
            back = "뒤로",
            abandoned = "연결이 끊어졌습니다",
            connectionError = "연결 오류",
            reconnecting = "재연결 중...",
            localMatch = "로컬 대전",
            goal = "내 말 3개를 연결하면 승리!",
            goalHint = "탭하여 자세히 보기",
            slideToEdge = "말을 가장자리까지 밀기",
            moveEmptyTile = "빈 타일 이동",
            rulesLabel = "규칙",
            boardLabel = "Hexlide 게임 보드",
            alertBoardSplit = "보드를 분리할 수 없습니다.",
            confirmRestart = "게임을 다시 시작하시겠습니까?",
            restart = "다시 시작",
            loading = "로딩 중...",
            aiThinking = "AI...",
            version = "버전",
            settings = "설정",
            language = "언어",
            howToPlay = "게임 방법",
            privacyPolicy = "개인정보 처리방침",
            contact = "문의하기",
            appWebsite = "앱 웹사이트",
            homepage = "홈페이지",
            webVersion = "웹 버전",
            writeReview = "리뷰 작성",
            done = "완료",
            followDeviceSetting = "기기 설정에 따르기",
            deleteLocalData = "로컬 데이터 삭제",
            deleteLocalDataConfirm = "플레이어 ID와 언어 설정이 초기화됩니다. 이 작업은 되돌릴 수 없습니다.",
            deleteLocalDataComplete = "로컬 데이터가 삭제되었습니다.",
            delete = "삭제",
            aiStats = "AI 대전 전적",
            statsWins = "승리",
            statsLosses = "패배",
            statsTotalGames = "합계",
            statsWinRate = "승률",
            statsAvgTurns = "평균 턴 수",
            statsNoGamesYet = "아직 전적 없음",
            statsGameHistory = "대전 기록",
            statsTurnsFormat = "%d턴",
            statsFirst = "선공",
            statsSecond = "후공",
        )

        // MARK: - Chinese (Simplified)
        val ZH_HANS = LocalizedStrings(
            aiMode = "AI 模式",
            pvpMode = "双人对战模式",
            onlineMode = "在线对战",
            selectMode = "选择模式",
            changeMode = "更改模式",
            you = "你",
            ai = "AI",
            opponent = "对手",
            playerRed = "红方",
            playerBlue = "蓝方",
            phaseMoveToken = "1. 滑动棋子",
            phaseMoveTile = "2. 移动板块",
            youWin = "你赢了！",
            aiWin = "AI 赢了！",
            opponentWin = "对手赢了！",
            redWin = "红方获胜！",
            blueWin = "蓝方获胜！",
            playAgain = "再来一局",
            yourTurn = "你的回合",
            opponentTurn = "对手的回合",
            decidingFirst = "正在决定先手...",
            onlineTitle = "在线对战模式",
            createRoom = "创建房间",
            joinRoom = "加入房间",
            createGame = "创建游戏",
            creating = "创建中...",
            waitingForOpponent = "等待对手中...",
            shareUrl = "将此 URL 分享给好友：",
            shareDescription = "将房间号或 URL 发送给好友。\n在应用中输入房间号，或打开 URL\n即可在网页上直接对战。",
            roomCodeLabel = "房间号",
            enterRoomCode = "输入房间号",
            roomCodePlaceholder = "例：123456",
            invalidRoomCode = "请检查房间号",
            copyUrl = "复制 URL",
            copied = "已复制！",
            joining = "加入中...",
            joinGame = "加入",
            gameNotFound = "未找到游戏",
            gameAlreadyStarted = "该游戏已经开始",
            endGame = "结束游戏",
            confirmEndGame = "确定要结束游戏吗？\n将断开与对手的连接。",
            cancel = "取消",
            confirm = "结束游戏",
            backToLobby = "返回大厅",
            back = "返回",
            abandoned = "连接已中断",
            connectionError = "连接错误",
            reconnecting = "重新连接中...",
            localMatch = "本地对战",
            goal = "将你的三个棋子连成一线即可获胜！",
            goalHint = "点击查看详情",
            slideToEdge = "将棋子滑至边缘",
            moveEmptyTile = "移动空板块",
            rulesLabel = "规则",
            boardLabel = "Hexlide 游戏棋盘",
            alertBoardSplit = "不能分裂棋盘。",
            confirmRestart = "重新开始本局游戏？",
            restart = "重新开始",
            loading = "加载中...",
            aiThinking = "AI...",
            version = "版本",
            settings = "设置",
            language = "语言",
            howToPlay = "游戏玩法",
            privacyPolicy = "隐私政策",
            contact = "联系我们",
            appWebsite = "应用官网",
            homepage = "主页",
            webVersion = "网页版",
            writeReview = "撰写评价",
            done = "完成",
            followDeviceSetting = "跟随系统设置",
            deleteLocalData = "删除本地数据",
            deleteLocalDataConfirm = "这将重置你的玩家 ID 和语言设置。此操作无法撤消。",
            deleteLocalDataComplete = "本地数据已删除。",
            delete = "删除",
            aiStats = "AI对战统计",
            statsWins = "胜利",
            statsLosses = "失败",
            statsTotalGames = "总计",
            statsWinRate = "胜率",
            statsAvgTurns = "平均回合数",
            statsNoGamesYet = "暂无对战",
            statsGameHistory = "对战记录",
            statsTurnsFormat = "%d回合",
            statsFirst = "先手",
            statsSecond = "后手",
        )

        // MARK: - Chinese (Traditional)
        val ZH_HANT = LocalizedStrings(
            aiMode = "AI 模式",
            pvpMode = "雙人對戰模式",
            onlineMode = "線上對戰",
            selectMode = "選擇模式",
            changeMode = "更改模式",
            you = "你",
            ai = "AI",
            opponent = "對手",
            playerRed = "紅方",
            playerBlue = "藍方",
            phaseMoveToken = "1. 滑動棋子",
            phaseMoveTile = "2. 移動板塊",
            youWin = "你贏了！",
            aiWin = "AI 贏了！",
            opponentWin = "對手贏了！",
            redWin = "紅方獲勝！",
            blueWin = "藍方獲勝！",
            playAgain = "再來一局",
            yourTurn = "你的回合",
            opponentTurn = "對手的回合",
            decidingFirst = "正在決定先手...",
            onlineTitle = "線上對戰模式",
            createRoom = "建立房間",
            joinRoom = "加入房間",
            createGame = "建立遊戲",
            creating = "建立中...",
            waitingForOpponent = "等待對手中...",
            shareUrl = "將此 URL 分享給好友：",
            shareDescription = "將房間號碼或 URL 傳給好友。\n在應用程式中輸入號碼，或打開 URL\n即可在網頁上直接對戰。",
            roomCodeLabel = "房間號碼",
            enterRoomCode = "輸入房間號碼",
            roomCodePlaceholder = "例：123456",
            invalidRoomCode = "請確認房間號碼",
            copyUrl = "複製 URL",
            copied = "已複製！",
            joining = "加入中...",
            joinGame = "加入",
            gameNotFound = "找不到遊戲",
            gameAlreadyStarted = "此遊戲已經開始",
            endGame = "結束遊戲",
            confirmEndGame = "確定要結束遊戲嗎？\n將中斷與對手的連線。",
            cancel = "取消",
            confirm = "結束遊戲",
            backToLobby = "返回大廳",
            back = "返回",
            abandoned = "連線已中斷",
            connectionError = "連線錯誤",
            reconnecting = "重新連線中...",
            localMatch = "本機對戰",
            goal = "將你的三個棋子連成一線即可獲勝！",
            goalHint = "點擊查看詳情",
            slideToEdge = "將棋子滑至邊緣",
            moveEmptyTile = "移動空板塊",
            rulesLabel = "規則",
            boardLabel = "Hexlide 遊戲棋盤",
            alertBoardSplit = "不能分裂棋盤。",
            confirmRestart = "重新開始本局遊戲？",
            restart = "重新開始",
            loading = "載入中...",
            aiThinking = "AI...",
            version = "版本",
            settings = "設定",
            language = "語言",
            howToPlay = "遊戲玩法",
            privacyPolicy = "隱私權政策",
            contact = "聯絡我們",
            appWebsite = "應用程式官網",
            homepage = "首頁",
            webVersion = "網頁版",
            writeReview = "撰寫評論",
            done = "完成",
            followDeviceSetting = "跟隨裝置設定",
            deleteLocalData = "刪除本機資料",
            deleteLocalDataConfirm = "這將重置你的玩家 ID 和語言設定。此操作無法復原。",
            deleteLocalDataComplete = "本機資料已刪除。",
            delete = "刪除",
            aiStats = "AI對戰統計",
            statsWins = "勝利",
            statsLosses = "敗北",
            statsTotalGames = "總計",
            statsWinRate = "勝率",
            statsAvgTurns = "平均回合數",
            statsNoGamesYet = "尚無對戰",
            statsGameHistory = "對戰記錄",
            statsTurnsFormat = "%d回合",
            statsFirst = "先手",
            statsSecond = "後手",
        )

        // MARK: - Spanish
        val ES = LocalizedStrings(
            aiMode = "Modo AI",
            pvpMode = "Modo 2 jugadores",
            onlineMode = "Modo en línea",
            selectMode = "Elegir modo",
            changeMode = "Cambiar modo",
            you = "Tú",
            ai = "AI",
            opponent = "Rival",
            playerRed = "Rojo",
            playerBlue = "Azul",
            phaseMoveToken = "1. Desliza una pieza",
            phaseMoveTile = "2. Mueve una casilla",
            youWin = "¡Has ganado!",
            aiWin = "¡AI gana!",
            opponentWin = "¡El rival gana!",
            redWin = "¡Rojo gana!",
            blueWin = "¡Azul gana!",
            playAgain = "Jugar de nuevo",
            yourTurn = "Tu turno",
            opponentTurn = "Turno del rival",
            decidingFirst = "Decidiendo quién empieza...",
            onlineTitle = "Modo en línea",
            createRoom = "Crear sala",
            joinRoom = "Unirse a sala",
            createGame = "Crear partida",
            creating = "Creando...",
            waitingForOpponent = "Esperando al rival...",
            shareUrl = "Comparte esta URL con un amigo:",
            shareDescription = "Envía el código de sala o la URL a un amigo.\nIngresa el código en la app o abre la URL\npara jugar de inmediato en la web.",
            roomCodeLabel = "Código de sala",
            enterRoomCode = "Ingresa el código de sala",
            roomCodePlaceholder = "Ej.: 123456",
            invalidRoomCode = "Revisa el código de sala",
            copyUrl = "Copiar URL",
            copied = "¡Copiado!",
            joining = "Uniéndose...",
            joinGame = "Unirse",
            gameNotFound = "Partida no encontrada",
            gameAlreadyStarted = "Esta partida ya ha comenzado",
            endGame = "Terminar partida",
            confirmEndGame = "¿Seguro que quieres terminar la partida?\nSe cortará la conexión con tu rival.",
            cancel = "Cancelar",
            confirm = "Terminar",
            backToLobby = "Volver al lobby",
            back = "Atrás",
            abandoned = "Conexión interrumpida",
            connectionError = "Error de conexión",
            reconnecting = "Reconectando...",
            localMatch = "Partida local",
            goal = "¡Conecta tus tres piezas para ganar!",
            goalHint = "Toca para más detalles",
            slideToEdge = "Desliza una pieza al borde",
            moveEmptyTile = "Mueve una casilla vacía",
            rulesLabel = "Reglas",
            boardLabel = "Tablero de Hexlide",
            alertBoardSplit = "No puedes dividir el tablero.",
            confirmRestart = "¿Reiniciar esta partida?",
            restart = "Reiniciar",
            loading = "Cargando...",
            aiThinking = "AI...",
            version = "Versión",
            settings = "Ajustes",
            language = "Idioma",
            howToPlay = "Cómo jugar",
            privacyPolicy = "Política de privacidad",
            contact = "Contacto",
            appWebsite = "Sitio web de la app",
            homepage = "Página de inicio",
            webVersion = "Versión web",
            writeReview = "Escribir reseña",
            done = "Listo",
            followDeviceSetting = "Seguir ajuste del dispositivo",
            deleteLocalData = "Eliminar datos locales",
            deleteLocalDataConfirm = "Se restablecerá tu ID de jugador y los ajustes de idioma. Esta acción no se puede deshacer.",
            deleteLocalDataComplete = "Los datos locales han sido eliminados.",
            delete = "Eliminar",
            aiStats = "Estadísticas IA",
            statsWins = "Victorias",
            statsLosses = "Derrotas",
            statsTotalGames = "Total",
            statsWinRate = "Ratio",
            statsAvgTurns = "Turnos prom.",
            statsNoGamesYet = "Sin partidas",
            statsGameHistory = "Historial",
            statsTurnsFormat = "%d turnos",
            statsFirst = "1.º",
            statsSecond = "2.º",
        )

        // MARK: - French
        val FR = LocalizedStrings(
            aiMode = "Mode AI",
            pvpMode = "Mode 2 joueurs",
            onlineMode = "Mode en ligne",
            selectMode = "Choisir un mode",
            changeMode = "Changer de mode",
            you = "Vous",
            ai = "AI",
            opponent = "Adversaire",
            playerRed = "Rouge",
            playerBlue = "Bleu",
            phaseMoveToken = "1. Glissez un pion",
            phaseMoveTile = "2. Déplacez une tuile",
            youWin = "Vous avez gagné !",
            aiWin = "L'AI gagne !",
            opponentWin = "L'adversaire gagne !",
            redWin = "Rouge gagne !",
            blueWin = "Bleu gagne !",
            playAgain = "Rejouer",
            yourTurn = "Votre tour",
            opponentTurn = "Tour de l'adversaire",
            decidingFirst = "Choix du premier joueur...",
            onlineTitle = "Mode en ligne",
            createRoom = "Créer un salon",
            joinRoom = "Rejoindre un salon",
            createGame = "Créer une partie",
            creating = "Création...",
            waitingForOpponent = "En attente de l'adversaire...",
            shareUrl = "Partagez cette URL avec un ami :",
            shareDescription = "Envoyez le code du salon ou l'URL à un ami.\nEntrez le code dans l'app, ou ouvrez l'URL\npour jouer directement sur le web.",
            roomCodeLabel = "Code du salon",
            enterRoomCode = "Entrez le code du salon",
            roomCodePlaceholder = "Ex. : 123456",
            invalidRoomCode = "Veuillez vérifier le code du salon",
            copyUrl = "Copier l'URL",
            copied = "Copié !",
            joining = "Connexion...",
            joinGame = "Rejoindre",
            gameNotFound = "Partie introuvable",
            gameAlreadyStarted = "Cette partie a déjà commencé",
            endGame = "Terminer la partie",
            confirmEndGame = "Voulez-vous vraiment terminer la partie ?\nLa connexion avec votre adversaire sera coupée.",
            cancel = "Annuler",
            confirm = "Terminer",
            backToLobby = "Retour au lobby",
            back = "Retour",
            abandoned = "Connexion interrompue",
            connectionError = "Erreur de connexion",
            reconnecting = "Reconnexion...",
            localMatch = "Partie locale",
            goal = "Reliez vos trois pions pour gagner !",
            goalHint = "Touchez pour plus de détails",
            slideToEdge = "Glissez un pion vers le bord",
            moveEmptyTile = "Déplacez une tuile vide",
            rulesLabel = "Règles",
            boardLabel = "Plateau de Hexlide",
            alertBoardSplit = "Vous ne pouvez pas diviser le plateau.",
            confirmRestart = "Recommencer cette partie ?",
            restart = "Recommencer",
            loading = "Chargement...",
            aiThinking = "AI...",
            version = "Version",
            settings = "Réglages",
            language = "Langue",
            howToPlay = "Comment jouer",
            privacyPolicy = "Politique de confidentialité",
            contact = "Nous contacter",
            appWebsite = "Site de l'app",
            homepage = "Page d'accueil",
            webVersion = "Version web",
            writeReview = "Écrire un avis",
            done = "Terminé",
            followDeviceSetting = "Suivre les réglages de l'appareil",
            deleteLocalData = "Supprimer les données locales",
            deleteLocalDataConfirm = "Votre identifiant joueur et vos paramètres de langue seront réinitialisés. Cette action est irréversible.",
            deleteLocalDataComplete = "Les données locales ont été supprimées.",
            delete = "Supprimer",
            aiStats = "Stats IA",
            statsWins = "Victoires",
            statsLosses = "Défaites",
            statsTotalGames = "Total",
            statsWinRate = "Ratio",
            statsAvgTurns = "Tours moy.",
            statsNoGamesYet = "Aucune partie",
            statsGameHistory = "Historique",
            statsTurnsFormat = "%d tours",
            statsFirst = "1er",
            statsSecond = "2e",
        )

        // MARK: - German
        val DE = LocalizedStrings(
            aiMode = "AI-Modus",
            pvpMode = "2-Spieler-Modus",
            onlineMode = "Online-Modus",
            selectMode = "Modus wählen",
            changeMode = "Modus wechseln",
            you = "Du",
            ai = "AI",
            opponent = "Gegner",
            playerRed = "Rot",
            playerBlue = "Blau",
            phaseMoveToken = "1. Spielstein schieben",
            phaseMoveTile = "2. Plättchen bewegen",
            youWin = "Du hast gewonnen!",
            aiWin = "AI gewinnt!",
            opponentWin = "Gegner gewinnt!",
            redWin = "Rot gewinnt!",
            blueWin = "Blau gewinnt!",
            playAgain = "Nochmal spielen",
            yourTurn = "Dein Zug",
            opponentTurn = "Zug des Gegners",
            decidingFirst = "Startspieler wird bestimmt...",
            onlineTitle = "Online-Modus",
            createRoom = "Raum erstellen",
            joinRoom = "Raum beitreten",
            createGame = "Spiel erstellen",
            creating = "Wird erstellt...",
            waitingForOpponent = "Warte auf Gegner...",
            shareUrl = "Teile diese URL mit einem Freund:",
            shareDescription = "Sende den Raumcode oder die URL an einen Freund.\nGib den Code in der App ein, oder öffne die URL,\num sofort im Web zu spielen.",
            roomCodeLabel = "Raumcode",
            enterRoomCode = "Raumcode eingeben",
            roomCodePlaceholder = "z.\u00A0B. 123456",
            invalidRoomCode = "Bitte überprüfe den Raumcode",
            copyUrl = "URL kopieren",
            copied = "Kopiert!",
            joining = "Beitritt...",
            joinGame = "Beitreten",
            gameNotFound = "Spiel nicht gefunden",
            gameAlreadyStarted = "Dieses Spiel hat bereits begonnen",
            endGame = "Spiel beenden",
            confirmEndGame = "Möchtest du das Spiel wirklich beenden?\nDie Verbindung zum Gegner wird getrennt.",
            cancel = "Abbrechen",
            confirm = "Beenden",
            backToLobby = "Zurück zur Lobby",
            back = "Zurück",
            abandoned = "Verbindung unterbrochen",
            connectionError = "Verbindungsfehler",
            reconnecting = "Verbindung wird wiederhergestellt...",
            localMatch = "Lokales Spiel",
            goal = "Verbinde deine drei Spielsteine, um zu gewinnen!",
            goalHint = "Tippen für Details",
            slideToEdge = "Schiebe einen Spielstein zum Rand",
            moveEmptyTile = "Bewege ein leeres Plättchen",
            rulesLabel = "Regeln",
            boardLabel = "Hexlide-Spielbrett",
            alertBoardSplit = "Das Brett darf nicht geteilt werden.",
            confirmRestart = "Dieses Spiel neu starten?",
            restart = "Neustart",
            loading = "Laden...",
            aiThinking = "AI...",
            version = "Version",
            settings = "Einstellungen",
            language = "Sprache",
            howToPlay = "Spielanleitung",
            privacyPolicy = "Datenschutzrichtlinie",
            contact = "Kontakt",
            appWebsite = "App-Website",
            homepage = "Startseite",
            webVersion = "Web-Version",
            writeReview = "Bewertung schreiben",
            done = "Fertig",
            followDeviceSetting = "Geräteeinstellung folgen",
            deleteLocalData = "Lokale Daten löschen",
            deleteLocalDataConfirm = "Deine Spieler-ID und Spracheinstellungen werden zurückgesetzt. Dies kann nicht rückgängig gemacht werden.",
            deleteLocalDataComplete = "Lokale Daten wurden gelöscht.",
            delete = "Löschen",
            aiStats = "KI-Statistiken",
            statsWins = "Siege",
            statsLosses = "Niederlagen",
            statsTotalGames = "Gesamt",
            statsWinRate = "Quote",
            statsAvgTurns = "Ø Züge",
            statsNoGamesYet = "Keine Spiele",
            statsGameHistory = "Spielverlauf",
            statsTurnsFormat = "%d Züge",
            statsFirst = "1.",
            statsSecond = "2.",
        )

        // MARK: - Portuguese
        val PT = LocalizedStrings(
            aiMode = "Modo AI",
            pvpMode = "Modo 2 jogadores",
            onlineMode = "Modo online",
            selectMode = "Escolher modo",
            changeMode = "Mudar modo",
            you = "Você",
            ai = "AI",
            opponent = "Adversário",
            playerRed = "Vermelho",
            playerBlue = "Azul",
            phaseMoveToken = "1. Deslize uma peça",
            phaseMoveTile = "2. Mova uma casa",
            youWin = "Você venceu!",
            aiWin = "AI venceu!",
            opponentWin = "Adversário venceu!",
            redWin = "Vermelho venceu!",
            blueWin = "Azul venceu!",
            playAgain = "Jogar novamente",
            yourTurn = "Sua vez",
            opponentTurn = "Vez do adversário",
            decidingFirst = "Decidindo quem começa...",
            onlineTitle = "Modo online",
            createRoom = "Criar sala",
            joinRoom = "Entrar na sala",
            createGame = "Criar jogo",
            creating = "Criando...",
            waitingForOpponent = "Aguardando adversário...",
            shareUrl = "Compartilhe esta URL com um amigo:",
            shareDescription = "Envie o código da sala ou a URL para um amigo.\nDigite o código no app, ou abra a URL\npara jogar na web instantaneamente.",
            roomCodeLabel = "Código da sala",
            enterRoomCode = "Digite o código da sala",
            roomCodePlaceholder = "Ex.: 123456",
            invalidRoomCode = "Verifique o código da sala",
            copyUrl = "Copiar URL",
            copied = "Copiado!",
            joining = "Entrando...",
            joinGame = "Entrar",
            gameNotFound = "Jogo não encontrado",
            gameAlreadyStarted = "Este jogo já começou",
            endGame = "Encerrar jogo",
            confirmEndGame = "Tem certeza que deseja encerrar o jogo?\nA conexão com o adversário será encerrada.",
            cancel = "Cancelar",
            confirm = "Encerrar",
            backToLobby = "Voltar ao lobby",
            back = "Voltar",
            abandoned = "Conexão interrompida",
            connectionError = "Erro de conexão",
            reconnecting = "Reconectando...",
            localMatch = "Partida local",
            goal = "Conecte suas três peças para vencer!",
            goalHint = "Toque para detalhes",
            slideToEdge = "Deslize uma peça até a borda",
            moveEmptyTile = "Mova uma casa vazia",
            rulesLabel = "Regras",
            boardLabel = "Tabuleiro do Hexlide",
            alertBoardSplit = "Você não pode dividir o tabuleiro.",
            confirmRestart = "Reiniciar este jogo?",
            restart = "Reiniciar",
            loading = "Carregando...",
            aiThinking = "AI...",
            version = "Versão",
            settings = "Configurações",
            language = "Idioma",
            howToPlay = "Como jogar",
            privacyPolicy = "Política de privacidade",
            contact = "Fale conosco",
            appWebsite = "Site do app",
            homepage = "Página inicial",
            webVersion = "Versão web",
            writeReview = "Escrever avaliação",
            done = "Concluído",
            followDeviceSetting = "Seguir configuração do dispositivo",
            deleteLocalData = "Excluir dados locais",
            deleteLocalDataConfirm = "Seu ID de jogador e configurações de idioma serão redefinidos. Esta ação não pode ser desfeita.",
            deleteLocalDataComplete = "Os dados locais foram excluídos.",
            delete = "Excluir",
            aiStats = "Estatísticas IA",
            statsWins = "Vitórias",
            statsLosses = "Derrotas",
            statsTotalGames = "Total",
            statsWinRate = "Taxa",
            statsAvgTurns = "Turnos méd.",
            statsNoGamesYet = "Sem jogos",
            statsGameHistory = "Histórico",
            statsTurnsFormat = "%d turnos",
            statsFirst = "1.º",
            statsSecond = "2.º",
        )

        // MARK: - Italian
        val IT = LocalizedStrings(
            aiMode = "Modalità AI",
            pvpMode = "Modalità 2 giocatori",
            onlineMode = "Modalità online",
            selectMode = "Scegli modalità",
            changeMode = "Cambia modalità",
            you = "Tu",
            ai = "AI",
            opponent = "Avversario",
            playerRed = "Rosso",
            playerBlue = "Blu",
            phaseMoveToken = "1. Fai scorrere una pedina",
            phaseMoveTile = "2. Sposta una casella",
            youWin = "Hai vinto!",
            aiWin = "L'AI vince!",
            opponentWin = "L'avversario vince!",
            redWin = "Rosso vince!",
            blueWin = "Blu vince!",
            playAgain = "Gioca ancora",
            yourTurn = "Il tuo turno",
            opponentTurn = "Turno dell'avversario",
            decidingFirst = "Scelta del primo giocatore...",
            onlineTitle = "Modalità online",
            createRoom = "Crea stanza",
            joinRoom = "Entra nella stanza",
            createGame = "Crea partita",
            creating = "Creazione...",
            waitingForOpponent = "In attesa dell'avversario...",
            shareUrl = "Condividi questo URL con un amico:",
            shareDescription = "Invia il codice stanza o l'URL a un amico.\nInserisci il codice nell'app, oppure apri l'URL\nper giocare subito sul web.",
            roomCodeLabel = "Codice stanza",
            enterRoomCode = "Inserisci il codice stanza",
            roomCodePlaceholder = "Es.: 123456",
            invalidRoomCode = "Controlla il codice stanza",
            copyUrl = "Copia URL",
            copied = "Copiato!",
            joining = "Ingresso...",
            joinGame = "Entra",
            gameNotFound = "Partita non trovata",
            gameAlreadyStarted = "Questa partita è già iniziata",
            endGame = "Termina partita",
            confirmEndGame = "Vuoi davvero terminare la partita?\nLa connessione con l'avversario verrà interrotta.",
            cancel = "Annulla",
            confirm = "Termina",
            backToLobby = "Torna alla lobby",
            back = "Indietro",
            abandoned = "Connessione interrotta",
            connectionError = "Errore di connessione",
            reconnecting = "Riconnessione...",
            localMatch = "Partita locale",
            goal = "Collega le tue tre pedine per vincere!",
            goalHint = "Tocca per i dettagli",
            slideToEdge = "Fai scorrere una pedina verso il bordo",
            moveEmptyTile = "Sposta una casella vuota",
            rulesLabel = "Regole",
            boardLabel = "Tavolo di gioco Hexlide",
            alertBoardSplit = "Non puoi dividere il tavolo.",
            confirmRestart = "Ricominciare questa partita?",
            restart = "Ricomincia",
            loading = "Caricamento...",
            aiThinking = "AI...",
            version = "Versione",
            settings = "Impostazioni",
            language = "Lingua",
            howToPlay = "Come giocare",
            privacyPolicy = "Informativa sulla privacy",
            contact = "Contattaci",
            appWebsite = "Sito dell'app",
            homepage = "Pagina iniziale",
            webVersion = "Versione web",
            writeReview = "Scrivi una recensione",
            done = "Fatto",
            followDeviceSetting = "Segui impostazione dispositivo",
            deleteLocalData = "Elimina dati locali",
            deleteLocalDataConfirm = "Il tuo ID giocatore e le impostazioni della lingua verranno reimpostati. Questa azione non può essere annullata.",
            deleteLocalDataComplete = "I dati locali sono stati eliminati.",
            delete = "Elimina",
            aiStats = "Statistiche IA",
            statsWins = "Vittorie",
            statsLosses = "Sconfitte",
            statsTotalGames = "Totale",
            statsWinRate = "Percentuale",
            statsAvgTurns = "Turni medi",
            statsNoGamesYet = "Nessuna partita",
            statsGameHistory = "Cronologia",
            statsTurnsFormat = "%d turni",
            statsFirst = "1°",
            statsSecond = "2°",
        )

        // MARK: - Russian
        val RU = LocalizedStrings(
            aiMode = "Режим AI",
            pvpMode = "Режим на двоих",
            onlineMode = "Онлайн-режим",
            selectMode = "Выбрать режим",
            changeMode = "Сменить режим",
            you = "Вы",
            ai = "AI",
            opponent = "Соперник",
            playerRed = "Красный",
            playerBlue = "Синий",
            phaseMoveToken = "1. Сдвиньте фишку",
            phaseMoveTile = "2. Переместите плитку",
            youWin = "Вы победили!",
            aiWin = "AI победил!",
            opponentWin = "Соперник победил!",
            redWin = "Красный побеждает!",
            blueWin = "Синий побеждает!",
            playAgain = "Играть снова",
            yourTurn = "Ваш ход",
            opponentTurn = "Ход соперника",
            decidingFirst = "Определяем, кто ходит первым...",
            onlineTitle = "Онлайн-режим",
            createRoom = "Создать комнату",
            joinRoom = "Войти в комнату",
            createGame = "Создать игру",
            creating = "Создание...",
            waitingForOpponent = "Ожидание соперника...",
            shareUrl = "Поделитесь этой ссылкой с другом:",
            shareDescription = "Отправьте код комнаты или ссылку другу.\nВведите код в приложении или откройте ссылку,\nчтобы играть через браузер.",
            roomCodeLabel = "Код комнаты",
            enterRoomCode = "Введите код комнаты",
            roomCodePlaceholder = "Напр.: 123456",
            invalidRoomCode = "Проверьте код комнаты",
            copyUrl = "Скопировать URL",
            copied = "Скопировано!",
            joining = "Подключение...",
            joinGame = "Войти",
            gameNotFound = "Игра не найдена",
            gameAlreadyStarted = "Эта игра уже началась",
            endGame = "Завершить игру",
            confirmEndGame = "Вы уверены, что хотите завершить игру?\nСоединение с соперником будет разорвано.",
            cancel = "Отмена",
            confirm = "Завершить",
            backToLobby = "Вернуться в лобби",
            back = "Назад",
            abandoned = "Соединение прервано",
            connectionError = "Ошибка соединения",
            reconnecting = "Переподключение...",
            localMatch = "Локальная игра",
            goal = "Соедините три свои фишки, чтобы победить!",
            goalHint = "Нажмите для подробностей",
            slideToEdge = "Сдвиньте фишку к краю",
            moveEmptyTile = "Переместите пустую плитку",
            rulesLabel = "Правила",
            boardLabel = "Игровое поле Hexlide",
            alertBoardSplit = "Нельзя разделить поле.",
            confirmRestart = "Начать эту игру заново?",
            restart = "Заново",
            loading = "Загрузка...",
            aiThinking = "AI...",
            version = "Версия",
            settings = "Настройки",
            language = "Язык",
            howToPlay = "Как играть",
            privacyPolicy = "Политика конфиденциальности",
            contact = "Связаться с нами",
            appWebsite = "Сайт приложения",
            homepage = "Домашняя страница",
            webVersion = "Веб-версия",
            writeReview = "Написать отзыв",
            done = "Готово",
            followDeviceSetting = "Как на устройстве",
            deleteLocalData = "Удалить локальные данные",
            deleteLocalDataConfirm = "Ваш ID игрока и языковые настройки будут сброшены. Это действие нельзя отменить.",
            deleteLocalDataComplete = "Локальные данные удалены.",
            delete = "Удалить",
            aiStats = "Статистика ИИ",
            statsWins = "Победы",
            statsLosses = "Поражения",
            statsTotalGames = "Всего",
            statsWinRate = "Процент",
            statsAvgTurns = "Ср. ходов",
            statsNoGamesYet = "Нет игр",
            statsGameHistory = "История",
            statsTurnsFormat = "%d ходов",
            statsFirst = "1-й",
            statsSecond = "2-й",
        )

        // MARK: - Thai
        val TH = LocalizedStrings(
            aiMode = "โหมด AI",
            pvpMode = "โหมด 2 ผู้เล่น",
            onlineMode = "โหมดออนไลน์",
            selectMode = "เลือกโหมด",
            changeMode = "เปลี่ยนโหมด",
            you = "คุณ",
            ai = "AI",
            opponent = "คู่แข่ง",
            playerRed = "แดง",
            playerBlue = "น้ำเงิน",
            phaseMoveToken = "1. เลื่อนหมาก",
            phaseMoveTile = "2. ย้ายแผ่นกระเบื้อง",
            youWin = "คุณชนะ!",
            aiWin = "AI ชนะ!",
            opponentWin = "คู่แข่งชนะ!",
            redWin = "แดงชนะ!",
            blueWin = "น้ำเงินชนะ!",
            playAgain = "เล่นอีกครั้ง",
            yourTurn = "ตาของคุณ",
            opponentTurn = "ตาของคู่แข่ง",
            decidingFirst = "กำลังเลือกผู้เริ่มก่อน...",
            onlineTitle = "โหมดออนไลน์",
            createRoom = "สร้างห้อง",
            joinRoom = "เข้าร่วมห้อง",
            createGame = "สร้างเกม",
            creating = "กำลังสร้าง...",
            waitingForOpponent = "รอคู่แข่ง...",
            shareUrl = "แชร์ URL นี้ให้เพื่อน:",
            shareDescription = "ส่งรหัสห้องหรือ URL ให้เพื่อน\nกรอกรหัสในแอป หรือเปิด URL\nเพื่อเล่นบนเว็บได้ทันที",
            roomCodeLabel = "รหัสห้อง",
            enterRoomCode = "กรอกรหัสห้อง",
            roomCodePlaceholder = "เช่น 123456",
            invalidRoomCode = "กรุณาตรวจสอบรหัสห้อง",
            copyUrl = "คัดลอก URL",
            copied = "คัดลอกแล้ว!",
            joining = "กำลังเข้าร่วม...",
            joinGame = "เข้าร่วม",
            gameNotFound = "ไม่พบเกม",
            gameAlreadyStarted = "เกมนี้เริ่มไปแล้ว",
            endGame = "จบเกม",
            confirmEndGame = "คุณแน่ใจหรือไม่ว่าต้องการจบเกม?\nการเชื่อมต่อกับคู่แข่งจะถูกตัด",
            cancel = "ยกเลิก",
            confirm = "จบเกม",
            backToLobby = "กลับสู่ล็อบบี้",
            back = "กลับ",
            abandoned = "การเชื่อมต่อถูกขัดจังหวะ",
            connectionError = "ข้อผิดพลาดในการเชื่อมต่อ",
            reconnecting = "กำลังเชื่อมต่อใหม่...",
            localMatch = "แข่งในเครื่อง",
            goal = "เชื่อมหมากสามตัวของคุณเพื่อชนะ!",
            goalHint = "แตะเพื่อดูรายละเอียด",
            slideToEdge = "เลื่อนหมากไปที่ขอบ",
            moveEmptyTile = "ย้ายแผ่นกระเบื้องว่าง",
            rulesLabel = "กติกา",
            boardLabel = "กระดาน Hexlide",
            alertBoardSplit = "ไม่สามารถแยกกระดานได้",
            confirmRestart = "เริ่มเกมนี้ใหม่หรือไม่?",
            restart = "เริ่มใหม่",
            loading = "กำลังโหลด...",
            aiThinking = "AI...",
            version = "เวอร์ชัน",
            settings = "การตั้งค่า",
            language = "ภาษา",
            howToPlay = "วิธีเล่น",
            privacyPolicy = "นโยบายความเป็นส่วนตัว",
            contact = "ติดต่อเรา",
            appWebsite = "เว็บไซต์แอป",
            homepage = "หน้าแรก",
            webVersion = "เวอร์ชันเว็บ",
            writeReview = "เขียนรีวิว",
            done = "เสร็จ",
            followDeviceSetting = "ตามการตั้งค่าอุปกรณ์",
            deleteLocalData = "ลบข้อมูลในเครื่อง",
            deleteLocalDataConfirm = "ID ผู้เล่นและการตั้งค่าภาษาจะถูกรีเซ็ต การดำเนินการนี้ไม่สามารถย้อนกลับได้",
            deleteLocalDataComplete = "ข้อมูลในเครื่องถูกลบแล้ว",
            delete = "ลบ",
            aiStats = "สถิติ AI",
            statsWins = "ชนะ",
            statsLosses = "แพ้",
            statsTotalGames = "ทั้งหมด",
            statsWinRate = "อัตราชนะ",
            statsAvgTurns = "เทิร์นเฉลี่ย",
            statsNoGamesYet = "ยังไม่มีเกม",
            statsGameHistory = "ประวัติ",
            statsTurnsFormat = "%d เทิร์น",
            statsFirst = "เดินก่อน",
            statsSecond = "เดินหลัง",
        )

        // MARK: - Vietnamese
        val VI = LocalizedStrings(
            aiMode = "Chế độ AI",
            pvpMode = "Chế độ 2 người",
            onlineMode = "Chế độ trực tuyến",
            selectMode = "Chọn chế độ",
            changeMode = "Đổi chế độ",
            you = "Bạn",
            ai = "AI",
            opponent = "Đối thủ",
            playerRed = "Đỏ",
            playerBlue = "Xanh",
            phaseMoveToken = "1. Trượt quân cờ",
            phaseMoveTile = "2. Di chuyển ô",
            youWin = "Bạn thắng!",
            aiWin = "AI thắng!",
            opponentWin = "Đối thủ thắng!",
            redWin = "Đỏ thắng!",
            blueWin = "Xanh thắng!",
            playAgain = "Chơi lại",
            yourTurn = "Lượt của bạn",
            opponentTurn = "Lượt của đối thủ",
            decidingFirst = "Đang chọn người đi trước...",
            onlineTitle = "Chế độ trực tuyến",
            createRoom = "Tạo phòng",
            joinRoom = "Vào phòng",
            createGame = "Tạo ván",
            creating = "Đang tạo...",
            waitingForOpponent = "Đang chờ đối thủ...",
            shareUrl = "Chia sẻ URL này với bạn bè:",
            shareDescription = "Gửi mã phòng hoặc URL cho bạn bè.\nNhập mã trong ứng dụng, hoặc mở URL\nđể chơi ngay trên web.",
            roomCodeLabel = "Mã phòng",
            enterRoomCode = "Nhập mã phòng",
            roomCodePlaceholder = "VD: 123456",
            invalidRoomCode = "Vui lòng kiểm tra mã phòng",
            copyUrl = "Sao chép URL",
            copied = "Đã sao chép!",
            joining = "Đang vào...",
            joinGame = "Vào",
            gameNotFound = "Không tìm thấy ván chơi",
            gameAlreadyStarted = "Ván chơi này đã bắt đầu",
            endGame = "Kết thúc ván",
            confirmEndGame = "Bạn có chắc muốn kết thúc ván chơi?\nKết nối với đối thủ sẽ bị ngắt.",
            cancel = "Hủy",
            confirm = "Kết thúc",
            backToLobby = "Quay lại sảnh",
            back = "Quay lại",
            abandoned = "Kết nối bị gián đoạn",
            connectionError = "Lỗi kết nối",
            reconnecting = "Đang kết nối lại...",
            localMatch = "Đấu cục bộ",
            goal = "Nối ba quân cờ của bạn để chiến thắng!",
            goalHint = "Nhấn để xem chi tiết",
            slideToEdge = "Trượt quân cờ đến mép",
            moveEmptyTile = "Di chuyển ô trống",
            rulesLabel = "Luật chơi",
            boardLabel = "Bàn cờ Hexlide",
            alertBoardSplit = "Không thể chia tách bàn cờ.",
            confirmRestart = "Bắt đầu lại ván này?",
            restart = "Bắt đầu lại",
            loading = "Đang tải...",
            aiThinking = "AI...",
            version = "Phiên bản",
            settings = "Cài đặt",
            language = "Ngôn ngữ",
            howToPlay = "Cách chơi",
            privacyPolicy = "Chính sách bảo mật",
            contact = "Liên hệ",
            appWebsite = "Trang web ứng dụng",
            homepage = "Trang chủ",
            webVersion = "Phiên bản web",
            writeReview = "Viết đánh giá",
            done = "Xong",
            followDeviceSetting = "Theo cài đặt thiết bị",
            deleteLocalData = "Xóa dữ liệu cục bộ",
            deleteLocalDataConfirm = "ID người chơi và cài đặt ngôn ngữ sẽ được đặt lại. Thao tác này không thể hoàn tác.",
            deleteLocalDataComplete = "Dữ liệu cục bộ đã được xóa.",
            delete = "Xóa",
            aiStats = "Thống kê AI",
            statsWins = "Thắng",
            statsLosses = "Thua",
            statsTotalGames = "Tổng",
            statsWinRate = "Tỉ lệ thắng",
            statsAvgTurns = "Lượt TB",
            statsNoGamesYet = "Chưa có trận",
            statsGameHistory = "Lịch sử",
            statsTurnsFormat = "%d lượt",
            statsFirst = "Đi trước",
            statsSecond = "Đi sau",
        )

        // MARK: - Indonesian
        val ID = LocalizedStrings(
            aiMode = "Mode AI",
            pvpMode = "Mode 2 Pemain",
            onlineMode = "Mode Online",
            selectMode = "Pilih Mode",
            changeMode = "Ganti Mode",
            you = "Kamu",
            ai = "AI",
            opponent = "Lawan",
            playerRed = "Merah",
            playerBlue = "Biru",
            phaseMoveToken = "1. Geser bidak",
            phaseMoveTile = "2. Pindahkan petak",
            youWin = "Kamu menang!",
            aiWin = "AI menang!",
            opponentWin = "Lawan menang!",
            redWin = "Merah menang!",
            blueWin = "Biru menang!",
            playAgain = "Main lagi",
            yourTurn = "Giliranmu",
            opponentTurn = "Giliran lawan",
            decidingFirst = "Menentukan siapa yang duluan...",
            onlineTitle = "Mode Online",
            createRoom = "Buat Ruangan",
            joinRoom = "Gabung Ruangan",
            createGame = "Buat Permainan",
            creating = "Membuat...",
            waitingForOpponent = "Menunggu lawan...",
            shareUrl = "Bagikan URL ini ke teman:",
            shareDescription = "Kirim kode ruangan atau URL ke teman.\nMasukkan kode di aplikasi, atau buka URL\nuntuk langsung bermain di web.",
            roomCodeLabel = "Kode Ruangan",
            enterRoomCode = "Masukkan kode ruangan",
            roomCodePlaceholder = "Cth: 123456",
            invalidRoomCode = "Periksa kode ruangan",
            copyUrl = "Salin URL",
            copied = "Disalin!",
            joining = "Bergabung...",
            joinGame = "Gabung",
            gameNotFound = "Permainan tidak ditemukan",
            gameAlreadyStarted = "Permainan ini sudah dimulai",
            endGame = "Akhiri Permainan",
            confirmEndGame = "Yakin ingin mengakhiri permainan?\nKoneksi dengan lawan akan terputus.",
            cancel = "Batal",
            confirm = "Akhiri",
            backToLobby = "Kembali ke lobi",
            back = "Kembali",
            abandoned = "Koneksi terputus",
            connectionError = "Kesalahan koneksi",
            reconnecting = "Menghubungkan kembali...",
            localMatch = "Pertandingan Lokal",
            goal = "Hubungkan tiga bidakmu untuk menang!",
            goalHint = "Ketuk untuk detail",
            slideToEdge = "Geser bidak ke tepi",
            moveEmptyTile = "Pindahkan petak kosong",
            rulesLabel = "Aturan",
            boardLabel = "Papan permainan Hexlide",
            alertBoardSplit = "Papan tidak boleh dipisahkan.",
            confirmRestart = "Mulai ulang permainan ini?",
            restart = "Mulai Ulang",
            loading = "Memuat...",
            aiThinking = "AI...",
            version = "Versi",
            settings = "Pengaturan",
            language = "Bahasa",
            howToPlay = "Cara Bermain",
            privacyPolicy = "Kebijakan Privasi",
            contact = "Hubungi Kami",
            appWebsite = "Situs Aplikasi",
            homepage = "Beranda",
            webVersion = "Versi Web",
            writeReview = "Tulis Ulasan",
            done = "Selesai",
            followDeviceSetting = "Ikuti pengaturan perangkat",
            deleteLocalData = "Hapus Data Lokal",
            deleteLocalDataConfirm = "ID pemain dan pengaturan bahasa akan direset. Tindakan ini tidak dapat dibatalkan.",
            deleteLocalDataComplete = "Data lokal telah dihapus.",
            delete = "Hapus",
            aiStats = "Statistik AI",
            statsWins = "Menang",
            statsLosses = "Kalah",
            statsTotalGames = "Total",
            statsWinRate = "Rasio Menang",
            statsAvgTurns = "Rata-rata giliran",
            statsNoGamesYet = "Belum ada permainan",
            statsGameHistory = "Riwayat",
            statsTurnsFormat = "%d giliran",
            statsFirst = "Pertama",
            statsSecond = "Kedua",
        )

        // MARK: - Turkish
        val TR = LocalizedStrings(
            aiMode = "AI Modu",
            pvpMode = "2 Kişilik Mod",
            onlineMode = "Çevrimiçi Mod",
            selectMode = "Mod Seç",
            changeMode = "Mod Değiştir",
            you = "Sen",
            ai = "AI",
            opponent = "Rakip",
            playerRed = "Kırmızı",
            playerBlue = "Mavi",
            phaseMoveToken = "1. Bir taşı kaydır",
            phaseMoveTile = "2. Bir karo taşı",
            youWin = "Kazandın!",
            aiWin = "AI kazandı!",
            opponentWin = "Rakip kazandı!",
            redWin = "Kırmızı kazandı!",
            blueWin = "Mavi kazandı!",
            playAgain = "Tekrar oyna",
            yourTurn = "Senin sıran",
            opponentTurn = "Rakibin sırası",
            decidingFirst = "İlk hamle belirleniyor...",
            onlineTitle = "Çevrimiçi Mod",
            createRoom = "Oda Oluştur",
            joinRoom = "Odaya Katıl",
            createGame = "Oyun Oluştur",
            creating = "Oluşturuluyor...",
            waitingForOpponent = "Rakip bekleniyor...",
            shareUrl = "Bu URL'yi arkadaşınla paylaş:",
            shareDescription = "Oda kodunu veya URL'yi arkadaşına gönder.\nUygulamada kodu gir veya URL'yi aç,\nhemen web üzerinden oyna.",
            roomCodeLabel = "Oda Kodu",
            enterRoomCode = "Oda kodunu gir",
            roomCodePlaceholder = "Ör: 123456",
            invalidRoomCode = "Lütfen oda kodunu kontrol et",
            copyUrl = "URL'yi Kopyala",
            copied = "Kopyalandı!",
            joining = "Katılınıyor...",
            joinGame = "Katıl",
            gameNotFound = "Oyun bulunamadı",
            gameAlreadyStarted = "Bu oyun zaten başladı",
            endGame = "Oyunu Bitir",
            confirmEndGame = "Oyunu bitirmek istediğinden emin misin?\nRakiple bağlantı kesilecek.",
            cancel = "İptal",
            confirm = "Bitir",
            backToLobby = "Lobiye dön",
            back = "Geri",
            abandoned = "Bağlantı kesildi",
            connectionError = "Bağlantı hatası",
            reconnecting = "Yeniden bağlanılıyor...",
            localMatch = "Yerel Maç",
            goal = "Üç taşını birleştirerek kazan!",
            goalHint = "Ayrıntılar için dokun",
            slideToEdge = "Bir taşı kenara kaydır",
            moveEmptyTile = "Boş karoyu taşı",
            rulesLabel = "Kurallar",
            boardLabel = "Hexlide oyun tahtası",
            alertBoardSplit = "Tahtayı bölemezsin.",
            confirmRestart = "Bu oyunu yeniden başlat?",
            restart = "Yeniden Başlat",
            loading = "Yükleniyor...",
            aiThinking = "AI...",
            version = "Sürüm",
            settings = "Ayarlar",
            language = "Dil",
            howToPlay = "Nasıl Oynanır",
            privacyPolicy = "Gizlilik Politikası",
            contact = "Bize Ulaşın",
            appWebsite = "Uygulama Web Sitesi",
            homepage = "Ana Sayfa",
            webVersion = "Web Sürümü",
            writeReview = "Değerlendirme Yaz",
            done = "Tamam",
            followDeviceSetting = "Cihaz ayarını takip et",
            deleteLocalData = "Yerel Verileri Sil",
            deleteLocalDataConfirm = "Oyuncu kimliğin ve dil ayarların sıfırlanacak. Bu işlem geri alınamaz.",
            deleteLocalDataComplete = "Yerel veriler silindi.",
            delete = "Sil",
            aiStats = "AI İstatistikleri",
            statsWins = "Galibiyet",
            statsLosses = "Mağlubiyet",
            statsTotalGames = "Toplam",
            statsWinRate = "Kazanma Oranı",
            statsAvgTurns = "Ort. Tur",
            statsNoGamesYet = "Henüz oyun yok",
            statsGameHistory = "Geçmiş",
            statsTurnsFormat = "%d tur",
            statsFirst = "İlk",
            statsSecond = "İkinci",
        )
    }
}
